#!/usr/bin/env python3
"""Build Run C radius-volume references from the p last points of cluster_tai instances.

The clustering instances generated by Prof. Taillard store the generator centers as the
p last coordinate rows. His reported quality ratios are measured relative to the solution
corresponding to these centers. This script computes that reference for every instance:

    assign every point to the nearest of the p last points
    for each cluster j, radius_j = max distance from its center to assigned points
    reference cost = sum_j radius_j ** d

The output zip is directly loadable by scripts/run_unified_pipeline.py for Run C.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd

INSTANCE_RE = re.compile(
    r"cluster_tai(?P<n>\d+)_(?P<p>\d+)_(?P<d>\d+)_(?P<instance_id>\d+)",
    re.IGNORECASE,
)
NUMBER_RE = r"[-+]?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?"


def parse_instance_name(name: str) -> dict[str, int | str] | None:
    base = os.path.basename(name)
    m = INSTANCE_RE.search(base)
    if not m:
        return None
    meta = {k: int(v) for k, v in m.groupdict().items()}
    meta["instance"] = m.group(0)
    return meta


def parse_cluster_tai_text(text: str, source_name: str):
    lines = [ln.strip() for ln in str(text).splitlines() if ln.strip()]
    if not lines:
        raise ValueError(f"Empty instance file: {source_name}")

    header_nums = re.findall(NUMBER_RE, lines[0])
    if len(header_nums) < 3:
        raise ValueError(f"First line must contain n p d in {source_name!r}; got {lines[0]!r}")

    n = int(float(header_nums[0]))
    p = int(float(header_nums[1]))
    d = int(float(header_nums[2]))

    coords = []
    for ln in lines[1:]:
        nums = [float(x) for x in re.findall(NUMBER_RE, ln)]
        if len(nums) < d:
            continue
        # If a row contains an index/metadata column, coordinates are the last d values.
        coords.append(nums[-d:])

    X = np.asarray(coords, dtype=float)
    if X.shape != (n, d):
        raise ValueError(f"Expected coordinates shape {(n, d)} in {source_name}, got {X.shape}")
    if p <= 0 or p > n:
        raise ValueError(f"Invalid p={p}, n={n} in {source_name}")
    if not np.all(np.isfinite(X)):
        raise ValueError(f"Non-finite coordinates in {source_name}")

    return X, n, p, d


def radius_power_cost_for_centers(X: np.ndarray, centers: np.ndarray, batch_size: int = 4096):
    X = np.asarray(X, dtype=float)
    centers = np.asarray(centers, dtype=float)
    if centers.ndim != 2 or centers.shape[1] != X.shape[1]:
        raise ValueError(f"Bad centers shape {centers.shape} for X shape {X.shape}")

    k = centers.shape[0]
    dim = X.shape[1]
    max_sq = np.zeros(k, dtype=float)
    counts = np.zeros(k, dtype=np.int64)

    for start in range(0, len(X), int(batch_size)):
        xb = X[start:start + int(batch_size)]
        diff = xb[:, None, :] - centers[None, :, :]
        dist2 = np.sum(diff * diff, axis=2)
        labels = np.argmin(dist2, axis=1)
        chosen = dist2[np.arange(len(xb)), labels]

        for j in np.unique(labels):
            mask = labels == j
            counts[j] += int(mask.sum())
            local_max = float(np.max(chosen[mask]))
            if local_max > max_sq[j]:
                max_sq[j] = local_max

    # max_sq_j = radius_j^2, so max_sq_j^(d/2) = radius_j^d.
    cost = float(np.sum(np.power(max_sq, float(dim) / 2.0)))
    return cost, counts


def build_reference(cluster_zip: Path, output_zip: Path, batch_size: int = 4096, limit: int | None = None) -> pd.DataFrame:
    if not cluster_zip.exists():
        raise FileNotFoundError(f"cluster_tai.zip not found: {cluster_zip}")

    rows = []
    with zipfile.ZipFile(cluster_zip, "r") as z:
        names = sorted(n for n in z.namelist() if INSTANCE_RE.search(os.path.basename(n)))
        if limit is not None:
            names = names[: int(limit)]
        if not names:
            raise RuntimeError(f"No cluster_tai*.csv files found in {cluster_zip}")

        for i, name in enumerate(names, start=1):
            base = os.path.basename(name)
            meta = parse_instance_name(base)
            if meta is None:
                continue

            text = z.read(name).decode("utf-8", errors="ignore")
            X, n, p, d = parse_cluster_tai_text(text, base)
            generator_centers = X[-p:].copy()
            cost, counts = radius_power_cost_for_centers(X, generator_centers, batch_size=batch_size)

            rows.append({
                "instance": meta["instance"],
                "n": n,
                "p": p,
                "d": d,
                "instance_id": int(meta["instance_id"]),
                "ref_radius_power_cost": cost,
                "reference_type": "generator_last_p_centers",
                "center_constraint": "snap_to_points",
                "uses_all_n_points": True,
                "min_assigned_count": int(counts.min()) if len(counts) else 0,
                "empty_centers": int(np.sum(counts == 0)) if len(counts) else 0,
            })
            if i % 25 == 0 or i == len(names):
                print(f"[{i}/{len(names)}] built generator reference for {base}", flush=True)

    df = pd.DataFrame(rows).sort_values(["d", "p", "n", "instance_id", "instance"]).reset_index(drop=True)
    if df.empty:
        raise RuntimeError("No references were generated.")

    output_zip.parent.mkdir(parents=True, exist_ok=True)
    tmp_dir = Path("/tmp") / f"generator_radius_reference_last_p_{os.getpid()}"
    if tmp_dir.exists():
        shutil.rmtree(tmp_dir)
    tmp_dir.mkdir(parents=True, exist_ok=True)

    main_csv = tmp_dir / "radius_volume_reference_generator_last_p.csv"
    alias_csv = tmp_dir / "radius_volume_reference_C1_generator_last_p.csv"
    df.to_csv(main_csv, index=False)
    df.to_csv(alias_csv, index=False)

    with zipfile.ZipFile(output_zip, "w", compression=zipfile.ZIP_DEFLATED) as z:
        z.write(main_csv, arcname=main_csv.name)
        z.write(alias_csv, arcname=alias_csv.name)

    print("\nCreated:", output_zip)
    print("Rows:", len(df))
    print("Reference type: p last points as generator centers")
    return df


def main():
    ap = argparse.ArgumentParser(description="Build Run C generator-last-p radius reference zip.")
    ap.add_argument("--cluster-zip", required=True, help="Path to cluster_tai.zip")
    ap.add_argument("--output-zip", required=True, help="Output reference zip path")
    ap.add_argument("--batch-size", type=int, default=4096, help="Distance batch size")
    ap.add_argument("--limit", type=int, default=None, help="Optional quick-test limit on number of instances")
    args = ap.parse_args()

    df = build_reference(
        cluster_zip=Path(args.cluster_zip),
        output_zip=Path(args.output_zip),
        batch_size=int(args.batch_size),
        limit=args.limit,
    )
    print(df.head(10).to_string(index=False))


if __name__ == "__main__":
    main()
